### ISSUE TITLE
server_url option

### ISSUE THREAD

**Issue by cmhk-Kelvin** [freewillfx-azenqos/azm_db_merge#3]
I found the comment in the code,
""" must be localhost only because now we're using BULK INSERT (or COPY) commands

Is it possible to have server_url option back, or where should i edit to support pointing the server_url?
Thanks~

**Comment by ykasidit** [comment]
Sorry the code was heavily modified since the time of that comment and I'm
quite sure it will not work in many cases we've handled since then sir. I
recommend to transfer the azm to the server instead then ssh to run
azmdbmerge in the server to get the required pg COPY mode working.

**Comment by ykasidit** [comment]
Update: Now it's possible - please specify server address through '--docker_postgres_server_name' option. (Now we still use COPY but through STDIN so no need for pg to have direct file access to the csv dump.
